"""comics table

Revision ID: 164473c21a13
Revises: 0042e4bffb28
Create Date: 2018-03-19 01:11:33.463815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164473c21a13'
down_revision = '0042e4bffb28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comic_name'), 'comic', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comic_name'), table_name='comic')
    op.drop_table('comic')
    # ### end Alembic commands ###
